### ISSUE TITLE
Hands models instead of controllers

### ISSUE THREAD

**Issue by ghost** [thojmr/HS2_BetterVR#1]
Hi, really appreciate it to see somebody working on further improving the VR experience for HS2.

A much requested feature would be to have fully working hand models instead of the controler models currently implemented.
Would it be possible to add this? 

Cheers.

**Comment by thojmr** [comment]
Hey, totally missed this since I assumed no one else had found this repo yet XD.  As for your request, it might be possible, but so far my efforts have been towards easy to implement quality of life changes.  I think adding the model for the hands would be simple enough as swaping the mesh, but as for the animations I can't be sure, since I've never done anything like that.  

Also I've only tested this with a Valve Index, so not sure about the other HMD's out there.

I'll see about building the latest version I have and adding a release for it here.

**Comment by ghost** [comment]
No problem! I am glad you found this :D
 
Totally understandable. It just would be something nice to have and i noticed no HS2VR mod does this currently. 

Hand animations would be awesome of course, but just switching the default controllers for hand models would do wonders already and fit quite nicely with the boop function you've added.

Since the game uses SteamVR and Unity, it might be not too much work for someone with experience. I am a total noob but while researching i found some threads about changing controller models for Unity, maybe there could be a lead (Idk how much access modders have to HS2 game files though).

By the way, i am using the Quest 2, so if you'd like, i can give you feedback for this device in the future (compatibility).

I noticed a small bug for the Quest already: Only one controller is working properly at a time (having the pointer to select things in the menu), when you press Y (controller 1) or B controller 2) it switches the pointer from one controller to the other.

The mod is still in my load order because the boop is just too awesome, but maybe you can look into that too! :)
